[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "liver-at-nnunet-v2"
version = "0.1.0"
description = "CBAM and Transformer extensions for nnU-Net v2"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.1"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["nnunet_at_v2*"]
